apiVersion: v1
kind: PersistentVolume
metadata:
  name: op-share-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-retain
  hostPath:
    path: /mnt/data/op-share
    type: DirectoryOrCreate
