apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: op-share-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 1Gi
  volumeName: op-share-pv
