apiVersion: v1
kind: PersistentVolume
metadata:
  name: overleaf-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/overleaf
    type: DirectoryOrCreate
