apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: overleaf
spec:
  hosts:
    - "overleaf.lth.so"
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: overleaf-service.overleaf.svc.cluster.local
            port:
              number: 80
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000; includeSubDomains
