apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slash-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    SLASH_DSN: AgC/q23WEiWpEOFyrNENJc1B2U7vQgP6GwntZ59XGpA1/gDDOIxkC+YhQhZeZT6cSfRaFCl61UeLQuzbwBoqoxEv/JmhfH/7HSbjIqCt4/E5CsWRSS6IT6QO8HCFQ8YmlDMYCqhv167/bpofvzyPXIWmaFRFVnhh2jziAFkMNbax9OLpc+JYL1lDMOVZ8LZKqc1ghQKvEa0f2A9qh8GtBe8llhScTeo+7FkaAiWF3Qp5QiLpIpEQFQRHc2O9AvzdSghHUTjDoidDG/g5Zn7Jy29pd2fEsrBts94dQjR6EdSu+bjT7WnAMPs/uKoroqSh9G9+FF2hOarhF5Z/P32zsYip9VwUqVllOPMUmX/k5bX6hg0VGNP2VaaXhNpWM+pMTMQI96RAMy3b8Wz8XwWPxqrpoMCXBVOa/PnV2COIu203Yhn5vChE0m3XZZuw3G1kGECi5BNFO0dJwsQAhdqexYNsSZZ4+vb+SsGqW6QtFbJweqOC+RB28lU2GEIiYsydmRAA5ggGlzud25kGECTkWVn/TCmhhkf3aYXDOIMJBTG9cZO7EoQYBt/PAIFrFgO0sjbCCYYB1sjJ8HT1juKeCtis4qMntck7lnpU23MrtYlDNN00AWKwUkwGcqXcJIdRgA9qz2sr8Q5u2XwG2MHhfsegyqJ+KJH3QWboAAiGqEmOBATMby1wTzJBUARWLUXS4hSzrkqOK2Z6owcDcJuPzRV1qHjj6BgzRUHb4N6loIwIT+v5mSQvier/38s3rYNMNpQXbUGfxGPX+PCqAEqLHCc99t7MZbe9CtNOVYU+sv2oKj0boL0=
  template:
    metadata:
      name: slash-secret
      namespace: slash