apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: slash
spec:
  hosts:
    - "s.lth.so"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - uri:
            exact: /
        - uri:
            prefix: /auth
        - uri:
            prefix: /shortcuts
        - uri:
            prefix: /collections
        - uri:
            prefix: /shortcut/
        - uri:
            prefix: /setting/general
        - uri:
            prefix: /setting/workspace
        - uri:
            prefix: /setting/subscription
        - uri:
            prefix: /s/
        - uri:
            prefix: /c/
        - uri:
            prefix: /assets/
        - uri:
            exact: /favicon.ico
        - uri:
            exact: /manifest.json
        - uri:
            exact: /robots.txt
        - uri:
            regex: ".+\\.(js|mjs|css|map|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf)$"
        - uri:
            prefix: "/slash.api"
      route:
        - destination:
            host: slash-service.slash.svc.cluster.local
            port:
              number: 5231
    - match:
        - uri:
            regex: "^/(.*)$"
      rewrite:
        uriRegexRewrite:
          match: "^/(.*)$"
          rewrite: "/s/\\1"
      route:
        - destination:
            host: slash-service.slash.svc.cluster.local
            port:
              number: 5231
