apiVersion: v1
kind: Secret
metadata:
  name: sure-secrets
type: Opaque
data:
  DB_PASSWORD: Y2hhbmdlbWU=
  SECRET_KEY_BASE: Y2hhbmdlbWU=
  OIDC_CLIENT_ID: Y2hhbmdlbWU=
  OIDC_CLIENT_SECRET: Y2hhbmdlbWU=
