apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: homelab
spec:
  commonUpdateSettings:
    updateStrategy: digest
  writeBackConfig:
    method: git
    gitConfig:
      repository: git@github.com:noeulnight/homelab.git
      branch: main
  applicationRefs:
    - namePattern: authentik
      images:
        - alias: authentik
          imageName: ghcr.io/noeulnight/authentik:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/authentik
    - namePattern: badges
      images:
        - alias: badges
          imageName: ghcr.io/noeulnight/kube-badges:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/kube-badges
    - namePattern: bridge
      images:
        - alias: bridge
          imageName: ghcr.io/noeulnight/bridge:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/bridge
    - namePattern: code-server
      images:
        - alias: code-server
          imageName: ghcr.io/coder/code-server:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/coder/code-server
    - namePattern: codex-lb
      images:
        - alias: codex-lb
          imageName: ghcr.io/aafqaq/codex-lb-enhanced:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/aafqaq/codex-lb-enhanced
    - namePattern: doclane
      images:
        - alias: backend
          imageName: ghcr.io/documentlane/doclane-backend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/documentlane/doclane-backend
        - alias: frontend
          imageName: ghcr.io/documentlane/doclane-frontend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/documentlane/doclane-frontend
    - namePattern: ghost
      images:
        - alias: ghost
          imageName: ghost:6-alpine
          manifestTargets:
            kustomize:
              name: ghost
    - namePattern: health
      images:
        - alias: api
          imageName: ghcr.io/noeulnight/health-api:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/health-api
        - alias: web
          imageName: ghcr.io/noeulnight/health-web:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/health-web
    - namePattern: kepco
      images:
        - alias: kepco
          imageName: ghcr.io/noeulnight/kepco:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/kepco
    - namePattern: korail
      images:
        - alias: backend
          imageName: ghcr.io/noeulnight/railroad-backend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/railroad-backend
        - alias: frontend
          imageName: ghcr.io/noeulnight/railroad-frontend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/railroad-frontend
    - namePattern: memos
      images:
        - alias: memos
          imageName: neosmemo/memos:canary
          manifestTargets:
            kustomize:
              name: neosmemo/memos
    - namePattern: n8n
      images:
        - alias: n8n
          imageName: docker.n8n.io/n8nio/n8n:stable
          manifestTargets:
            kustomize:
              name: docker.n8n.io/n8nio/n8n
    - namePattern: ntfy
      images:
        - alias: ntfy
          imageName: binwiederhier/ntfy:latest
          manifestTargets:
            kustomize:
              name: binwiederhier/ntfy
    - namePattern: obsync
      images:
        - alias: api
          imageName: ghcr.io/noeulnight/obsync-api:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/obsync-api
        - alias: web
          imageName: ghcr.io/noeulnight/obsync-web:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/obsync-web
    - namePattern: osmproxy
      images:
        - alias: osmproxy
          imageName: ghcr.io/noeulnight/osmproxy:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/osmproxy
    - namePattern: pmail
      images:
        - alias: server
          imageName: ghcr.io/pmh-only/mail:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/pmh-only/mail
        - alias: worker
          imageName: ghcr.io/pmh-only/mail-worker:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/pmh-only/mail-worker
    - namePattern: root
      images:
        - alias: root
          imageName: ghcr.io/noeulnight/root:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/root
    - namePattern: sikdae
      images:
        - alias: backend
          imageName: ghcr.io/noeulnight/sikdae-backend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/sikdae-backend
        - alias: frontend
          imageName: ghcr.io/noeulnight/sikdae-frontend:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/sikdae-frontend
    - namePattern: slash
      images:
        - alias: slash
          imageName: yourselfhosted/slash:latest
          manifestTargets:
            kustomize:
              name: yourselfhosted/slash
    - namePattern: spotify
      images:
        - alias: server
          imageName: ghcr.io/noeulnight/spotify-stat-server:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/spotify-stat-server
        - alias: web
          imageName: ghcr.io/noeulnight/spotify-stat-client:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/spotify-stat-client
        - alias: canvas
          imageName: ghcr.io/noeulnight/spotify-canvas-api:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/spotify-canvas-api
    - namePattern: technitium
      images:
        - alias: server
          imageName: technitium/dns-server:latest
          manifestTargets:
            kustomize:
              name: technitium/dns-server
        - alias: exporter
          imageName: ghcr.io/noeulnight/technitium-exporter:master
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/technitium-exporter
    - namePattern: termix
      images:
        - alias: termix
          imageName: ghcr.io/lukegus/termix:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/lukegus/termix
    - namePattern: timeline
      images:
        - alias: timeline
          imageName: freikin/dawarich:latest
          manifestTargets:
            kustomize:
              name: freikin/dawarich
    - namePattern: tunnel
      images:
        - alias: api
          imageName: ghcr.io/noeulnight/hole-api:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/hole-api
        - alias: web
          imageName: ghcr.io/noeulnight/hole-web:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/noeulnight/hole-web
    - namePattern: wakapi
      images:
        - alias: wakapi
          imageName: ghcr.io/muety/wakapi:latest
          manifestTargets:
            kustomize:
              name: ghcr.io/muety/wakapi
