apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tunnel
  template:
    metadata:
      labels:
        app: tunnel
        app.kubernetes.io/version: v1
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: server
          image: ghcr.io/noeulnight/hole:latest
          ports:
            - containerPort: 3000
            - containerPort: 2233

          env:
            - name: DOMAIN
              value: tunnel.lth.so
            - name: HTTP_PORT
              value: "3000"
            - name: SSH_PORT
              value: "2233"
            - name: SSH_AUTH_MODE
              value: noauth
            - name: TUNNEL_PORT_RANGE
              value: 40000-50000
            - name: SSH_HOST_KEY_PATH
              value: /data/host.key
          volumeMounts:
            - mountPath: /data
              name: tunnel-storage
      volumes:
        - name: tunnel-storage
          persistentVolumeClaim:
            claimName: tunnel-pvc
