apiVersion: v1
kind: PersistentVolume
metadata:
  name: timeline-postgres-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/timeline/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: timeline-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/timeline/storage
    type: DirectoryOrCreate
