apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustfs-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/rustfs/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustfs-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/rustfs/logs
    type: DirectoryOrCreate
