apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    COUCHDB_USER: AgAo3vpGsumgYctzLzi3b23blZQ/gPDZmYLWq8XlVjXf+jByseg3IDDrW2c0NdoIXL5+BrmFyrPqOtf1TPDflgIzxUC2U4Qf7831nzyNWvwMCdkCU3G5jmGqkYH0Sanvc3VGXk9NYZH8m9g/mk4gOrKouPJ9dDmq1kXwtiAJqMwFKDX4rGEnFu54+pG6p0COMPGhq2zrq4rgBEwAF4ZutSVLlIrZIjs9Exo7GcIvIUWcJM/a42Y3a2eP6Kvfim4EriNuD2mc2j9lnCzJP/L97JSwSOIhkXdloREu/MNS2fHT/IWDN/DfdqJXgMYJx7ah4rMNy7FbE4N1SB9o/Ee8CQrlJKwrnM9ko9C5Lw7OHND7P5jDVEv1xXvlbO6RUjqP5HAz+lh/4ZTUiCbNZ7IBREmG97SIy1y4Phw5kSrbmJ3u79lOVr4g79GiE+5i9wYTm7ew2R65MLUKYGer0dPf14Nf7udWNqFgu7WYFrv7ne/uhlFef9L4qFBkyuelVc9jI7Y508+wmN/vgdCX/zmS1RnzCwX1ABuM5ZLE71Q4EABQpRlYIfgFOod57W0Vf1EWc0DlhcGS1B+OhkxqTWBVeYnJBlWiabW+OApsw+x8RezRtQ5QvDJlgPIghpqsxa6j8AElhDH0XFxDEvpLtSG+IQ/k36gkSVtp7DuMEFyML8q5fsHHO8lcmN1BNeI1NAB6QJVJfks/YQ==
    COUCHDB_PASSWORD: AgCEr1JUADfDLQ7Fsun8XwhZPuPbuTbz9y8uIwfzSnfxZYGnFASsV+3AOu4n+WWCvYqNbw8fTS22Y2/k/CzyyPyofmXFj9LyH/P+Uz/eeYCjPg01PRBXo5PRRQQfHpwZ9ndAcjhFgQBgxKhILvnbWrOZTyEWOfu2PglhaICtIDgQsu5ugZfKk5wMZD4hVseXz/bjim88c6KxmodFG2QbNChIY4Pn+oyOhRRVzRGEkrE2n1exCrFOVlHfsnh7/gAVf5jTOEU7eO5YI0MwlHRPysRoTqmE/376ABaP21PPAOZGP5AshPzjNWYGX7VRVSetdcPHN8vXMFGX0H/pZGwBVD4Cya+8RCyuhYySJ48b2D4hYDiRRnRe4MuFhAE+uIb8ssQsxPwui+JTbfZt3uJOW8ibNfqLDkbefk1P6JTkHbXQfHwrGcBDoMBcZJx/sk8pfMnBXbwzuB5cAk8teN2ZZRP8yTgWcX7TJWYyG59lyd7a83LoEJsxlmK5h6oVPImA/XiEmGzjnHy8jvHqMRP/YltbTa4I20P+shr8gewPABsoUOKuQ6bC9YJPqEZQHE3vJkDpWjzraRkyt7vgBORbA9I9dtbwW01ZqMHFIqAZczSFva+AJ58vwOljpfJcyTMEG4TNIFFBU3UTUgtfIo7LflfSiTWweqh/jGp2jNzMrxBiWZgYzlq3xZT8rY/YNRO85Hyi3Q8UhbowBxKb
  template:
    metadata:
      name: couchdb-secret
      namespace: couchdb
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
