apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: couchdb
spec:
  hosts:
    - "couchdb.lth.so"
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: couchdb-service.couchdb.svc.cluster.local
            port:
              number: 5984
