apiVersion: v1
kind: Service
metadata:
  name: lobehub
spec:
  selector:
    app: lobehub
  ports:
    - name: http
      port: 3210
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: lobehub-postgres
spec:
  selector:
    app: lobehub-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
