apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: lobehub
spec:
  hosts:
    - lobe.lth.so
    - gateway.lth.so
    - lobhub-gateway.lth.so
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - authority:
            exact: gateway.lth.so
      route:
        - destination:
            host: lobehub.lobehub.svc.cluster.local
            port:
              number: 8787
    - match:
        - authority:
            exact: lobhub-gateway.lth.so
      route:
        - destination:
            host: lobehub.lobehub.svc.cluster.local
            port:
              number: 8788
    - route:
        - destination:
            host: lobehub.lobehub.svc.cluster.local
            port:
              number: 3210
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000; includeSubDomains
