apiVersion: v1
kind: PersistentVolume
metadata:
  name: traccar-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/traccar/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traccar-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/traccar/data
    type: DirectoryOrCreate
