apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traccar-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: traccar-logs-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traccar-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: traccar-data-pv
  resources:
    requests:
      storage: 20Gi
