apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vitwarden-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: vitwarden-pv
  resources:
    requests:
      storage: 10Gi
