---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: alertmanager-n8n
  namespace: prometheus
spec:
  encryptedData:
    url: AgA6NTi97oyziQvDIpTjGPNEkoITEMFzT5V9N41SEG3m9sE9LtQJ/CacCFGJpKWHRb/MCHZV3VSjGMCS712KyqRlYyEC4MlLV/v9eE0k23kn0TuwvkOhzgXjP/knfOEIfUBXK/vpR6pw1ra/iS3CrtVNBRQgJVPU27/HxGxfZrAJuc3ezVYKNMA5iUFWe8HYc+cHwQaPxPFoTccqslDu9XxMJaD5Ig5c5xRLygcE8nul9fpkXpCXHNTWNBBurYm6VjPyaeLKZWPCFHjG5ZPJ2au/KptHLvyn0YYzUDK1uwGOHMEtmgTjBQHzyQGq483zAoDLAo3XpVWzJ13+pC3jIfHTLLSwLPHKXd2NX9R9Ys6VlZeiDgqdNLfRrLGErvho0DNc3997V1kE6X+ezPZRZUXNPuGPrp6VJYdxFfMRIZfuD98tPwI/B5oxr9fi0PQGlijULXheD1k5Q8yovBG8FvY9lwAT1I4WBqBOFyZsrr4gTmsPrirHP80cUh9auc1Znt5qm9OEFRws3UCLoAnW2PgtGbf1h9JHY1AtZ2aHRl6M2J+EJxHuycePEXgeqkpBDQnBUWHXwfhGKTfU/KGNM1/kfjAVgZ4+laU9+B/A/mLYZIQAei1yWPHeTVXgqEd/WMg+9vH6X2kHp99YvDvEuxkkc1V+eqgsiYYNPOApXT3a/r+FTMQdWcI2AtAldhV1/QUGbgcgAz9NZYv5pCgx9RgtFE4g14EuZ4/n6XYSoIDyjOMXUk0slkjahN4aHTgZi75R3YkN4xQGxt7GGFpcU4XRIgg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: alertmanager-n8n
      namespace: prometheus
