apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: prometheus-secrets
  namespace: prometheus
spec:
  encryptedData:
    WAKAPI_TOKEN: AgBOKXEQXprMpkIUPqigb2e3FeBBpEKipHhHOTLP5EwMJ2BfvGa2x/thOT09QXwMqbhZ6gy8dVilNXS73wqGO9l8pxAfRuyrz2G+5U6FlD1rsOo1coaLrNYWAN2DUpCDo618AxhU0R4ToZqemdDGxcGkGFQrMUHi02wns+auXJyN7rNbH+qROCTr1twGjSnQxPSrWJpbjC9ZCG8P4dRvsaMlgzWIY0y1Eyv7NnItIPdNxJgEAlTLRMZecngkoPFoYfudRIlkagi+KVZQMFUwFXZ64OjkrQavg2P1TIA7KWcoYaJt+RDArxF1I/gP8htRa6jLoC/yQk1t+/o+WA642YwH7d1KYYRZUqSgd29AK3N5zMJquds8W/20TBANyTanFXxvDXw2PyAodpQqQolGCT0UH438cmMFKmB9WzJwb3auI4De/vG4yR63ETr+IDcQPpixn/NEDxHhie2/IQXvhVAR5ciWPMiFlRffuOKBTBvkDboqqTrsC/s8fk2T3xn3XqTlX6VPNag8qKifGe5nkd13IQnW+nWUCUEXMjyYUsZ7firzVtWd0gTFbLRQGqxfWpKOcedshQz2xuF6Epsu57jZPCJp8PiZYUl2AHi1k7vvD+NFKCVELmHH0IO3OdU6iS1LVhQ5bSNcQbw46ZvnOpNy5xaA7VWEC533x6P9P4mIh+9cjtosATkir/CaSRzOok4kMoQsll6BWdt/JH+sIPII/B5ZSyRwu545/MWn90PyRRBqvrvRpu8Zd+eS5eO3m/qn3gnV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: prometheus-secrets
      namespace: prometheus
    type: Opaque
