apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      initContainers:
        - name: init-admin
          image: binwiederhier/ntfy
          command: ["/bin/sh", "-c"]
          args:
            - |
              timeout 2 ntfy serve >/dev/null 2>&1 || true
              ntfy user add --ignore-exists --role=admin noeulnight
          env:
            - name: NTFY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ntfy-secret
                  key: NTFY_ADMIN_PASSWORD
            - name: NTFY_WEB_PUSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ntfy-secret
                  key: NTFY_WEB_PUSH_PRIVATE_KEY
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy
              readOnly: true
            - name: data
              mountPath: /var/cache/ntfy
      containers:
        - name: ntfy
          image: binwiederhier/ntfy
          args: ["serve"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
            - name: metrics
              containerPort: 9090
          env:
            - name: NTFY_ATTACHMENT_CACHE_DIR
              valueFrom:
                secretKeyRef:
                  name: ntfy-secret
                  key: NTFY_ATTACHMENT_CACHE_DIR
            - name: NTFY_WEB_PUSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ntfy-secret
                  key: NTFY_WEB_PUSH_PRIVATE_KEY
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy
              readOnly: true
            - name: data
              mountPath: /var/cache/ntfy
      volumes:
        - name: config
          configMap:
            name: ntfy
        - name: data
          persistentVolumeClaim:
            claimName: ntfy-pvc
