apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: ntfy-pv
  resources:
    requests:
      storage: 5Gi
