apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/technitium
    type: DirectoryOrCreate
