apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: adguard
spec:
  hosts:
    - "adguard.lth.so"
    - "adguard.limtaehyun.dev"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - headers:
            :authority:
              exact: adguard.limtaehyun.dev
      redirect:
        authority: adguard.lth.so
    - match:
        - uri:
            exact: /signin
      redirect:
        uri: /outpost.goauthentik.io/sign_out
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ak-outpost-adguard.authentik.svc.cluster.local
            port:
              number: 9000
