apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: n8n
spec:
  hosts:
    - "workflow.lth.so"
    - "workflow.limtaehyun.dev"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - headers:
            :authority:
              exact: workflow.limtaehyun.dev
      redirect:
        authority: workflow.lth.so
    - match:
        - uri:
            exact: /signin
      redirect:
        uri: /outpost.goauthentik.io/sign_out
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: ak-outpost-n8n.authentik.svc.cluster.local
            port:
              number: 9000
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000; includeSubDomains
