apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/authentik
    type: DirectoryOrCreate
