apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
data:
  AUTHENTIK_SECRET_KEY: eW91c2hhbGxub3RwYXNz
  AUTHENTIK_EMAIL__PASSWORD: eW91c2hhbGxub3RwYXNz
  AUTHENTIK_POSTGRESQL__PASSWORD: eW91c2hhbGxub3RwYXNz
