apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmail
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmail
  template:
    metadata:
      labels:
        app: pmail
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: pmail
          image: ghcr.io/pmh-only/mail:latest
          ports:
            - name: web
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: pmail-secret
