apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: korail-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    DATABASE_URL: AgB/fvF2mLlBjNF97ugTOJd/fb0M74fA0SqOJW5FCfe4dmd+nRPKxkvmxd6/9GmfnBevC5caDBYvsIjQjAbRmxKmnt+hoRXPjJm7E+NwjSjkjpTIJ4VidxsHfUlVPg8nHecpZgnoHrsYoUwOdOX4a+Vv1ADI+rRbeUTWerwTryWv9ypl9fuzIy3kfevLpHGYNp03FxOjN7RKESSstNsivRRgUFhm7QAREWBty2RVscb2rzm+TTFpAmx1c99U0l/Tsq0br/L8oNF1IB1ikAy0PZJoWCxEh9zvrN9fZ2rRjnO1HJfYL5XOnJ50I3OgLk3vI9iYngmy0yoNVbIgpXZ9xRheK2fbKHaBGheuPBUZukLhpn4xcpy2oikktlYaClNT6vBPzjAaxAArj/R06F1yA449/PP2VUipLngt75cEHKFJIwttRHMksM58X7Q5As9UTmMzOdwUA65zIvUcSiffXxy1Nmuq6iHYKTGk8z4Dpp3bi3QqoiS22hhTAZp3QjZGxnnwYSyfSB5ikEg/DdNGztEhgsWWdyQQexErn4ApHSkAxb7x2w+zJ7dbpLjyEda1UZlZpVyIrPl0PBCXGpruE3N8IXiLfwWQTWrPL4WNpPiLFl48wfvjMZ/1/UmTZXUHi3GfQL7QBDhZmIT15AQjd4dKGATskdsPc1YoRdGvze7vBfnN1Tp/0ejKYtIlMsP6RCCYyGVvade3/Yfh0BDR9cA9eOeOa877SG0qrg5T7Z+S630wYbWhLSppW0Z55+pzWBkuuwttWas/hWxVGH1Kqq4GfaYOTrGGfirwh1vYA9XN
  template:
    metadata:
      name: korail-secret
      namespace: korail
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
