apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path-retain
  volumeName: immich-library-pv
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path-retain
  volumeName: immich-db-pv
  resources:
    requests:
      storage: 20Gi
