apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: korail-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    DATABASE_URL: AgCCrJPiEL7gp9PzyAaqBnx/haAjkVCd4FMobYEzXlF4++7Wq+PGa8EQfQLCOWZA/OWNVRiFmkgmtpadUOZuLu4yMojBzm2d3FS8jHGx5ADeI+An6G1zF5GtN5msE7xZ3VQrdaS8sWq16lQi4KsgjoHgwRtygYJA8OLGMEm5t30xg/Pm7zdJLyB/Lc3bWst0YQswRzV40MNkiDnWOBT46Jx1+ObFH7A58LP6eNRs1ZRuZq8bVqStfsmHHCl21xVkSzNOy+NFCG1Cw+cmaKbozO4Iubvrq4KL4McsGhTJcJqSFVxozAc03uf8eyhCb+XZgoGql8pEsYtRZ1x8qMLWP2o8mYxTS+HeBmtk73TGlCZGRaSw+qewM/zukuaRhrV0Daarf6jZI6w0tstESj/3K75EWz/hF1VdbHdfIk/x4OO8ZgxcYQOd7oZi20ptls81O/hSgQ+l+kibbwza5YjXAWmlVO53FOOLCCQM5IAX8V/c8ufoeOcuSfajvzIODRxMVmo47dSRVmnqLP/N/djDNO8OARSZhY4esxeGVr+temEESzMNc8NRm9y/CLJBsGLZiWTZfJw081gSPZ121nXbvB2XsRod3bNZhFBjUSvHInR/3EknLl3yKG4Jt9r099OET2hu1GOe56IteeHv3Cl1qo5MWU7KlE0R6AXiWPFblEKe2KujoGmdIbEYTtUjwGrj633uKmfGrA1l1ff2rHQDMTESlLrWQeb4iv9YmXmHA/BN6YfuBPy463y0RE0AXwvWCaecNKvuU50CPHvm9yZom/5X4/CDI0nCu51nc81DxZfw
  template:
    metadata:
      name: korail-secret
      namespace: korail
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
