apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codex-lb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: codex-lb-pv
  resources:
    requests:
      storage: 5Gi
