apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: adguard-work-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: adguard-conf-pv
  resources:
    requests:
      storage: 1Gi
