apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrier-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kurrier/db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrier-typesense-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kurrier/typesense
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrier-dav-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kurrier/dav
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrier-webdav-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kurrier/webdav
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrier-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kurrier/storage
    type: DirectoryOrCreate
