apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrier-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: kurrier-db-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrier-typesense-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: kurrier-typesense-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrier-dav-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: kurrier-dav-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrier-webdav-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: kurrier-webdav-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrier-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: kurrier-storage-pv
  resources:
    requests:
      storage: 20Gi
