---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-secret
spec:
  encryptedData:
    CLICKHOUSE_PASSWORD: AgBbMBuB9p4q4oxtS4kYtbZDvtceHpZBRTi88oOA4Dtubi9/GxlXoZ1+U0BqtdxpCB4Ag8iQIKag3/z6IuFezC80hdKTC7tede81oTU49/rKhScqokBF3ebaXG0xo/28uvJdLl8+JjB/uwgoyOLIoBUfTO5VSleQ0Ybuqr/kMPB+KarLlgQhhvL+jPKDlWh5ZS9xhAXZddoK7PT1gFsubnixraBz41wvkGgXSWZyVEMKm2sdGqVFVHQ0BrUGwRxSfRegzbhy88j27DzIdwgtrG+aIgn2CHIVTVtsiCac5W1bTvPYZlDF/GEeDahiLrKRM5seJBQ/jvzive3BzV9Vj108fD1LLJsp5b53x+p1K+w63Qba32yKit4BWHwWIllLsGa+F0r7oX23Vohi6Oj4on7Krc5zT85d26ymBfjf8QFxnpAi8pOaKortSRTxl7mPVZIbOvnDVRdDUEREg1wTN6kTn4uFzDaQ2Xv87rbuLqi4Y+c/iCnVOUHD22f36iwnTioUwnkHRhaZR8Eh+qqqFAoooEBZCt+/4T5n4kPWw01eCE8BW0QCGx5z8V3Ri00s4rWGamXRz/4w2r6qyuLgXz/NRo2mohg7HUtqrX7yyKa+YLobgk0Xmwpa97cdzYvFD+BY3vUUdshJJPuTTSL0jh4BxyIdI78yDoaQTyzhz8fgkQtSbZHIk9DhSel8urooQdpfk1+fel9hW+KE
  template:
    metadata:
      name: clickhouse-secret
      namespace: clickhouse
