apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timeline-postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  volumeName: timeline-postgres-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timeline-storage-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path-retain
  volumeName: timeline-storage-pv
  resources:
    requests:
      storage: 20Gi
