apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bridge-secret
spec:
  encryptedData:
    BRIDGE_WEB_ADMIN_PASS: AgBRsagSQhlm+izqqyhq2tDT8qaGDtRHuLnAU3mydKx3ErgRbv33eKAYblbRFBXUBx+cT9hpxuaLDXLP1kjPfenDaQIacj3LyIG9ZzkjR8VzV3/dhMYYy0bHOLT9388P8L5E3g44edQjScxDM+0ejPbp3kegqZSoBCHnV3bYYqGAfKalWbd4mck4lqOoOGxIDE5xUVLpCn5xIeNV++rrlySY7izpLDiCglemKnfp1M461+kjI2zgeeaKuVmpuq9NK5R9R/59nELo9t0x5ntNcZ2MmSoieO5aGXrjUuHSjSxoc1SnsLeodyarll7lhTkgNqZBqVyNnxMiyGfvO8HKHsQuz+y6QPiJWZxm/xKwPw3DfuwGlYbsDJ9nSqSun9p+uiJfvRH5NKsV/XeSmovkPrbR8R2B/txgXfw8rZLk1GL02KjYd7jUE178GsXhXja8lwQFnUM6Ck2rSdlDobWeilyinXuuC1uwGB3i1A/+ipoLdwlno3cRhP4Ru+dOwlVG/kuwp8+VcidkTxTQZb+l4qt1/BtI3mAonZK71GB+Tg3fibjj+ykph7Iu2LVN4q4TQ/NqRR4mspAdxiKaFkITL1A4htUUBXpvLV+auEvT/gfbdxeoFnYfSIWc7Efo/CqNMBHG1KGu98siSB3aRuwy7a6LbuheDAbDimcPIeAzDV7pLNv/ecDyYmKuA5wbDJPjdU3/4jFe5qi+1QEc
  template:
    metadata:
      name: bridge-secret
      namespace: bridge
