apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: public-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: lth-tls
      hosts:
        - "*.lth.so"
        - "*.coder.lth.so"
        - "lth.so"
        - "*.limtaehyun.dev"
        - "limtaehyun.dev"
