apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: server
          image: ghcr.io/noeulnight/root
          ports:
            - containerPort: 8080
          env:
            - name: WAKAPI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: root-secret
                  key: WAKAPI_API_KEY
            - name: GHOST_CONTENT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: root-secret
                  key: GHOST_CONTENT_API_KEY
