apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: root-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    WAKAPI_API_KEY: AgCwAJNXftQr59dWid2jcbOkYwCqOxImFErn4THvlx+M8WWvWCvihFkahh8s1vUSEBuGGoO4I5RsdFOQ57wpCyL/ta+bAh/GxwwOnH/y4IbuEQ7yD89xXY2AbYCXC5kPrWrzI9e3Db+lcHbb0Ve0k9hGHhADFoW5NguXTO0W1rZ35+xghrvJt0j/U/b5x7sfziVpqllxcdJcWSqZtkwXT/a7pvNXyqr7bqR+XYX0uPekFDKPbsl2Y9f2GnXuPg1ETo1Axw+BPsHCieuHh5SipulJ3T/EtOoaqHKKkHQY9FtT1ZQwbsNa+aF8uXBqSLG0SLLNXf6e/NJFi5vt/757NFoV9ekG+CUOjEDlnPZTMS7w/YoSytnmyYkHnYTqlc5YU69KEyvxhIYZZHi5hsrWG6Ys4jR9te6yX0lg+PAzVXP34qewVKoB7ZjluT9eJGo2UJPb1pz1EbITMQrvpOpRhc4PM7m+FfcI4UUe5wE6ndpKo17DOw81vM5tdln1vBTgbXVJvv7yibWBkWVczFmu7ijt5Erurpu2gmrF6Al3tpuTUbLp5bBx+//UuVsB3D/+ZA6sD2YPbqzs+4R5xnuRdt6tfbFFKw3diKoozCqbiRhVyraZIq2P/SlTDlq07O6HSq7YATnwNtiX2sMENteN3XCBYfekwtFHGgi4DcVMEfvHSMV8eC2fHAsyjSyJB8n3VPWjULIshomumsCD0LljFYdwfwRK3Duz+XhsbU4nahDSlBo6dmc=
    GHOST_CONTENT_API_KEY: AgCpNW06EheHgTKU1K+uLNuOToQIjH2YXZlI8AKuLs9iZV8umsIzMRGRxXkwDqbTKqJ5DVql9o/vqI/jkuiExZfikqguIoAUYTai0TWqGrBB52Mq7wqxEsxlAMVTk9vd4+zyhPZyxNpIm4ABLDHy/nX3vdNq9DE0iWJdAPBzK6HosVD/COn2TYD+BjNPywFfjgUbX7BusA/sKZRy6rqk1Zgu0psuimw3vBxWtM7+bC5HhxoN9IjFWZv5V96Km5pvkmaHzYTwbF/bUKP3sdvKw56iqbUJqp+w2+CzDCkLDGgJ6RG0y2bxkL8DoEm81euDgl6/8jf4WPrl88P2W0FHlngmCKL7w2DYiV6wnbsJV091au5SiC7trbrbZb6fgk1hGtXhTf+Y7PC4ThPy9O425VgLC0FO28dEMnS8/4Hjn0cjkab5JOXFGIvL4W8S0fmcgJSuFeI0h7gEB6RINQ7nGJEtCdSpXh1CKEQoydJWryHnXTH/9c0Sih6kuAMItHSE5KkpAuTFoBPZtR9OhYop6WLgUGA9+WAYbHyW7fdwq0L0fXq7IcWTNUpZF3Mzce/HQHcXFbllYU0AWKYX7PRZX0/qkOLn58Bq/FhtQJDRtJqd4B75+SRg7XE/w9I7Zui9KhJFViX8oTmIRGA4Ug0GlWhUOGEPmxe6WSmIGmy39fSEXzg9w4Uq1+WtOhlmXru+lWrCaijbREHBBKVwxZg3HkOsHrMNOyvQxMVXdA==
  template:
    metadata:
      name: root-secret
      namespace: root
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"