apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: root
spec:
  hosts:
    - "lth.so"
  gateways:
    - istio-ingress/public-gateway
  http:
    - match:
        - uri:
            prefix: /s/
      redirect:
        authority: s.lth.so
