apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
data:
  client_id: Y2hhbmdlbWU=
  client_secret: Y2hhbmdlbWU=
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    TAILSCALE_OAUTH_CLIENT_ID: AgBF/2W7i1TAFwpg6zaKyDFx9nG/hY394SBA2c9V9J5CFK5zbVY6FKJfwbkrxjtEG8PF2xh+C8jpyR6qevi8HqIhwcx4lpf3pb7pgAIqvibYsC1vlQECmUrrB5tkSwMWfJKLDlI17SnjkJWbTq1SLCPGAItjO6LC7aFI7eonZ8He7y/6/411hHft+8CkG8RtDzj8CmQ0t/gKElZ5Gct+yWdrdJ3U7wZrsZdOatzCWYoXnkDXQy+sp/BdmVy14zKAD64FID6B6ERWj0hRymyEBtwab9fEsJraSw++BIqblLDzpK+LMdczDKMC4zmi4iuiAG8QNLXUx13MdPG2wwwmbziV8X43w6Vc2xL+ZhpBszoead3kiTsMHbxvIev6OrehgjbVhiKGV7k/K9lodyPa19lHWsuPxbmlpZ6uYV0P8IJ+4VspI83Y37hRcJpDf1NVwRCDrAymUubKtz29PiYLc/ybO9hWBpCmQHvrFijjw+KQTHANLhSYZBIfpTkd3h/jhsJ9oxNmNLQdrp3jMpyJpioT8Qqb+JIP++0OUDvUM2l8Kquj9vg1gsSM8D5sl+0zCNbrswovK8lfhpBLziNvjZM4ba+8XAf9ei7cGExtAXaFQyBTnEhmh3yE+qEwcnaREf+MpahRTzT4bqGAaTjk8nMtWtMHrcOjF5Lw6O2jNan19ipT6bXgLsDrQxPyohs4zYXRHNRVQPLbS9BEXyU+uzHyAw==
    TAILSCALE_OAUTH_CLIENT_SECRET: AgAiNbGRGUUdRDaieaPirXswMh5XPrmYwa4bAPBRa3b4xWwTRaq6xRNUwJc9eURvPlIQLkunSTJRUE7UTudgF7EaO0Udo241mVlmu3VdDCbTV1TYTuWru6PcefcrftLqgAsrIIT+0zRHh8DEdkxH90vgZMtKrF/Auaw5dkXXrC2mFwVe7kOegHjC7avGt2mfoTxId0S39Zl7Kowv4IDWksPgxn/erR7Nl4JYyXnK2PQ/ABlxLQMZo1B3DzpQyX0eGmh43VenTicGvdnLbVkDvGjKxlfH4sKI/sm83pGIKSeAeKFf76J9FREOcpBRNXNpphTHkrm3fqQqTKUcCdoxHhgAz1JOkNr45oNvWH4fk4+rJnGjHvar98ciJBdFovOyyjC1qL0Yj/3eyCegEvFCYZgkNDTGvu1lrA0b7jWtqFSN+ZJ2CVoqfxHBnRvVbKtKfwmXk/8murGZAZj0CUhqE/LUHysCZy1J8tXNgKbUMeHitedCyPuMJHxijLSV+9iZgk/XxJHoG9IMNr8P4Sj8RTUVQOem6ZlbNwlVB79OlPoCKblv18OWMj5Jt6UN/YcJB6fc8DHtgRZKIS25JpbS4CDEoLoXEuMnzFzFNDK7jeBOmHhxRPJ77u48ukwFVJa4g4paCVcvHfKZB2ou73WC4nt+Cn1b0d/RAcoEa8UAu6gw+z0dwaW4OvQBDJ44SEkU6G2aUn3L48GTjS1YsLyN9cY9e0c63DD14Emt1aJ1/+rFE4Nizole/NfxZZsOx/gxDmFJGIhJOID77oaF2Z49IgOz