apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
data:
  TS_AUTHKEY: Y2hhbmdlbWU=
---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
data:
  client_id: Y2hhbmdlbWU=
  client_secret: Y2hhbmdlbWU=
