apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: limtaehyun-pi.tail6de6ea.ts.net
  name: pi
spec:
  externalName: pi
  type: ExternalName
  ports:
    - name: homebridge
      port: 8000
      protocol: TCP
    - name: ssh
      port: 22
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: limtaehyuns-mac-mini.tail6de6ea.ts.net
  name: mac-mini
spec:
  externalName: mac-mini
  type: ExternalName
  ports:
    - name: vnc-tcp
      port: 5900
      protocol: TCP
    - name: vnc-udp
      port: 5900
      protocol: UDP
    - name: ssh
      port: 22
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tailscale-exporter
  labels:
    app.kubernetes.io/name: tailscale-exporter
spec:
  selector:
    app: tailscale-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9250
      targetPort: 9250
