apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: badges-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - services
      - namespaces
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs: ["get", "list"]
