apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
        - name: outline
          image: docker.getoutline.com/outlinewiki/outline:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/outline/data
              name: outline-storage
          env:
            - name: NODE_ENV
              value: production
            - name: URL
              value: https://outline.limtaehyun.dev
            - name: PORT
              value: "3000"
            - name: DEFAULT_LANGUAGE
              value: ko_KR
            - name: DATABASE_URL
              value: postgres://outline:outline@postgres-service.postgres.svc.cluster.local:5432/outline
            - name: REDIS_URL
              value: redis://redis-service.redis.svc.cluster.local:6379
            - name: FILE_STORAGE
              value: local
            - name: FILE_STORAGE_LOCAL_ROOT_DIR
              value: /var/lib/outline/data
            - name: FORCE_HTTPS
              value: "false"
      volumes:
        - name: outline-storage
          persistentVolumeClaim:
            claimName: outline-pvc
