apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
type: Opaque
data:
  SECRET_KEY: eW91c2hhbGxub3RwYXNz
  UTILS_SECRET: eW91c2hhbGxub3RwYXNz
  OIDC_CLIENT_ID: eW91c2hhbGxub3RwYXNz
  OIDC_CLIENT_SECRET: eW91c2hhbGxub3RwYXNz
