apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: health-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    HEALTH_API_TOKEN: AgAfGL/Lag4R0YrikOQqgNmaQatcApUONdMdf2E8Mv3QruEcXlu7d3Xc1F0FojUStIjjN/k5aTrNWyaOcLWDNsUnhKkIQ+1pANfuySHN1mPRq/XAOS003JFHjkLV+1a+VWtkF3HEUdaQOKFim7POWyP17GBi+eHbJatVxAA23GU3RdiUPyLpdYXdF+b5XgiKxUSmLCVOudKSjRAlQWZxGbrr5WdDOemOn9bIADvuNTUejIE4Qsjt4JIB9lMuGNhhyGGZt3OIwKLaXlbkH3KBLFZj9EY3tcmJ1eML2qGFH5DVW7nRyo9FOV3otp/hRL1iY4n2eX1ZjV8gCZmrnSkwlp2MeUJ70ckNKcd7enMO4wS7rJ94WMA6LCh/QaQYTwoMq4w1Flp1Wox/XgU9esTEHE86zs0zXexlzbhPhVqEKYPu/402zv8F2eCOpfK7lOFCk57zCmOl4C/nzfaJ5Jl//M0I7eRntL7PIeX5CpuwtCgM1mbWUZ/Jkum/VQy2OfU2u8nEiYK0ujkHOTegACfteJvyKcxC8xSqaAlufB1xdkSqKuI3lipN09ib5nzSapmdPweCz2WnDXZAn8YilDA8leX4Xp3GAPxlSSsAjPW3gpFsFBzfaOqVguVbBuq9GaD5l6+qU2hAsVr4zNL4MuvUr2WtFRIoAGWlyRhOkZyEfNIWuRqsaPl89ITcv3zmKqg7ClEwM34zKu5BdMktkiaHykKrlFkrYAwwWfesAVeFk+9nmxtdnTPQNlqGUXoxhP11ZVKFu67QCR2Q8ph/MdkOxG8R
  template:
    metadata:
      name: health-secrets
      namespace: health
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
