apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc
  labels:
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc
  template:
    metadata:
      labels:
        app: vnc
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: server
          image: ghcr.io/noeulnight/novnc:latest
          ports:
            - containerPort: 6080
          env:
            - name: VNC_SERVER
              value: mac-mini.tailscale.svc.cluster.local:5900
            - name: VNC_USERNAME
              value: limtaehyun
            - name: VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vnc-secret
                  key: VNC_PASSWORD
            - name: AUTOCONNECT
              value: "true"
