apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vnc-secret
  namespace: vnc
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    VNC_PASSWORD: AgDkQJ7FglHimjkhapCPBYpEEBsQ4cLXQPT9BftXL/GDwtgXcn9waG3bwKln97QEpYQiH+8GSd8w1utbq13zDD4c8ziV3cywBd4mMPdsvAdTkob7YsgOHBPxjilKyOMl/pogD5Uz+n3ArVJhtNqZreqvgl2lWJxS60UniKOGOn04eIcPPwERvDA+IkxhRztCTk0O8Qi9HdQescaIm0rlmkMF3ipnXILrWRMoH5/reODuUEBmyF7rSOEtZrj3Cgt8IGPUBXN6Otdc+AQJW7KTZJwH44SuMbXp5widZEJUcXsHL9ZLmPQynIA+iq+bOCAcHM2yFu4xUnJuFHDNbpt90AUFEw2S8gNw9cW8lQMLHjDG1HvMO6gKTuEuDdAUEcgHY6KYqvqU7j4MpEpzKF3VCycQgf+mVHdNvuDJn/kRcJT+FADvSJAwEblePGYQwvV09tK7PGy2zFXR9TVZxaVZhhIMXqVck7VVYf+zCB+9lGa3ndnrAZJc6bVERnP6WkhcVMLj3LiWqvC/8/kJN2JT7ZbBK3YlecNRsoX7czrb8K+M+lChr6OqvibUnxd1suM5YWDreJVFJh3J3QxlmqsmUgIuZp6NSUD0QHczZd0PMJ/RiwyroKJ5cc6TI/2ANAVEiRL8p8BW87wSx9WoNpLsq20KNH4BYRf/8RUDSO9B8qdh2uD2VfRFZQpKgh+FXArMSQV/+P3fCqINsvFkER9HdXa1
