apiVersion: v1
kind: Service
metadata:
  name: vnc-service
  labels:
    app.kubernetes.io/name: vnc-service
spec:
  selector:
    app: vnc
  ports:
    - name: http
      protocol: TCP
      port: 6080
      targetPort: 6080
