---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kepco-secret
  namespace: kepco
spec:
  encryptedData:
    KEPCO_ID: AgAi2rhZS5fUpMpsIbtwxwFktKIHhmw7+61jX8uYo7ccdNPT+g3K2EaOrD/5UajjfBLUrTw1aUBJ0NhU2t9YvaJKJ7BES95bayHfW4SfdeWbi2sgAkte0RZo8eBddIhZ3qUIIMgjEN3EXWoADyLBQoyJpC5Ho7ez4G8EjyejPX0Qy/CuXwjc/jE9rixfgtzuYUgyfwLVT1U5a+120TDDS5QcoT0x35dG/hY5mxyawuh+mLOK357UAYG7CJNlvL/U5yRaQzFjSqFSUJwVF3WreKxS5jpiGSM9nFOYPja1BbvgU5r4Hqn2gP/nSGhBMPrRz2gnFZ7X+MOi6Y2P2cYyHVjSxKm8nX6Erq8efkUGelknT2JjaLeQtjNyXWjGZDyBQCE/Kl8W8EoFsdTdDF5Z9lTw+dXWKo0HpZR5hqlQYBvsC0Xwk2lnzn8zNe6lnqhzhS6lnm8kshVWIG8KqO6/suDV8ez60xWLle8BaVQUk6PqsCmU+haPQgpv1q5sbAt+zsMyIHzqD80lsQxrEs0q7wizs1X7m+SqzGKiOBNKkishJ6jo/Gi+CuKO9hDppHKBLRwTW/41gPHkSwyJRxi9Vetk1sAkfxlHGYeRT/eBFg6F+zByt44uEuEHk9yjSijoQNjTDnlf/vnB/UxBuEqfeprUNy8Gy/T72/f80ZhUHzyZLgO6qrfXBECNFruXoKBWhMfVUJPAJrbUonax
    KEPCO_PW: AgCeeuJA7Q+MJ0KgFXoSj5rHe3rhsBl+zdA7hurGsLfISZMGVVyzcZX6RM0lZF9sTO3f7juufLic9HyBwB4mWkmFy0C3mEOwYuPilfOXnhbOVLHT/gS9HJKGoj+26TEpLvTJL8TR8HLxiJd3Oo33lPUoJird3CbDc0Pxc7OpX7L5MTTdlNHeU38X4ztR5I4OE0g1PCQITK+rVdJ0qdiYdNEL6SrY3/eTYjauXC7fZqc8kbMwktL7UJBantptPpWh9YkkNqnff6QVgQ8Gfwgq3MWWgqUd9U7nUrj778DyKpIBals4M6tSRzeIimSPZe1DmEaBfELD1Oi0Y11GwcfMjLVxShrH0ElWr39Cf9mwXevrwaVdFEz8kckda5WNPkESHiYBgtA71F8gicGypGTxV+RC/iMkdDWx+V7h0FrN5/75fIIgPvXDbpZGcj1NEkMvyDD4J9AUqSSpbpV6HBhFaHergifcfwuc2iFn1tXJ8gxJ4UcqRG/Km7+NN+IkC/hAIniKrIM/HWPDP+Ty4ZSoaZ23evbxHJxKI9aJ1wVZ45gfi0wh7L5U4o3D0GxYQi83jtAyI467LVDOmvexZJcLYWdKUbCoSOSvgvLLYfOLphn2cc+RCWDYUPiD9zEy/pUQY3njq+V5V0UVbPseMMeTt+F2czvycXlU8k9BNRgGtXede2EoghqxF1tG6khFecbhB4SZgebiVE65qX7IAhk=
  template:
    metadata:
      name: kepco-secret
      namespace: kepco
