---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spotify-secret
  namespace: default
spec:
  encryptedData:
    SPOITFY_PUBLIC: AgA2VyGAZUzrmGVswMRCIWsJsQEMLAjhmSWtxk7GHxsgrykzNUY2NQ7Yw4WeOzxIGB9LKlbFNEJxxLjX/WGbtFufybMehED8YRCxizFV5y7qBr8Emc6sD0bi04FSJBXQINmzCgUXTpdJvdFg2H27xHjs3MG/cP/FKIlaPQ8v8QszYZjSlViYl1pXhf4YDfPwCYJWxYHDZVA75e2pIhGSX36mcVTw8Pa/+jfLGGzImLGO+eEvMpr+mNXZDirA0XlsD+okzMPyxMBbtguT5cyXWR4M0Jk4Rq6Xc7jsYEjt9S5dzLParBwAO3qlVdrEczUKbgtBXn4XLStzq2PqeS/HjqGLEIfvbm9nzg+E2xt3uN3cuWd1u8UvgBxeW5QrEAh4KRGzujZCd8qsI+eVs0xmkEo0j6Cmdj1BNOKzt2EzI3E1m2Bg7/KhidT6Z41f6BXLmrQ2oPvguitv2YgWJ+GI4ljpIY4yvpYIFe3UiCTd9NxMA5wl2OXaml2D8zlBvdMeB5/zyYR0iwDd/PW4A7Ay5jXHQnXqPAB7rUpCkAb5OVgPd/Abf/fhYdgMjlbR72peotHeoGvo+L0/hmkfI7uTim+ASSZBwePb/tNMqjlQVZLWL+vVBdPdk7fK/SSbo+EKTNUAmkIv6tfN96h9kgCt2XN0+JJelxjGzSdlrR0VlcfjDNF9CVs1+O5aTgpVc9q3k5Zoy/LwymYQnFrh1/UHMJzt+27kTnsV4rb2C+o8djO4TA==
    SPOTIFY_SECRET: AgBY5wwXIBNRRPvHbXjxk+0xMeOnOWIyucgc3Y91N8oTrAkOPSEO7eLFpmFA9EgdJoF8n89ReaTs4CQvYdu6mO+8CteDC4ix3HkLLjTF5eatKoFjjUfIo7cIyzvydyj9oRkVu1VavTrMTWbjg7qTxjuxPf2v7z1cLQsr0zWnp1baP18i2MrQRlKitLnG3wvBSaTDfQ/OgJ2jN4p8aiA2bUWYeVyv3yJPgQviUiTnJuoSlByQnaDJbLsGW979bOoSxCJ7vB+u5OS03Syfvw6cMRWwAopQrRcT4HzMjqpvH9AO7sl/BLlP7h/TDk9KQkQZ/cnJUnQHNJe2E80WQPM9j93Dn0KTtvu6Yqd9D8oTEwzuqb5hrwa/mk9m+WzyoUZuo0nVcuLwfmxl/k9PGH3cvUSuV+vMJiSbRKrDJ1rZ/m0AT0+G6wGC/SP9YA1JlsuhMYDIW0+b5/QHOyaJhylzZlb9kqqVRFoYMc03ZZoc9zZdYhFLBkeR6vB/QjbERZoU8URJSUTU65WipS9LhZe4gaSjoi/cBtCHyqC5Ev0dEaeW7HaH32SLOoien+mVhgBFjYlJrQr8yDfxF9qzHCRJPylvod4tqBL4oWqI0Prc+mwlGpyl9T79NwcdNqm3nyV5Vg/3QwzO6ZUkNkks01VVmcqT/9ZotwDuPpAVdW0QIWTtfc8hTW2P6iXH0Yoh1x51MR9Vvt9Q1MihaFsx8lFa0sMD9lLUhjeAo5+PxRSO4JmUFA==
  template:
    metadata:
      name: spotify-secret
      namespace: default
