apiVersion: v1
kind: Secret
metadata:
  name: wakapi-secrets
type: Opaque
data:
  WAKAPI_PASSWORD_SALT: "YXdqZm5wb3Zhaml3ZW9hZmF3ZG9maXZqYg=="
  WAKAPI_DB_PASSWORD: "d2FrYXBp"
  WAKA_OIDC_CLIENT_ID: "eW91c2hhbGxub3RwYXNz"
  WAKA_OIDC_CLIENT_SECRET: "eW91c2hhbGxub3RwYXNz"
  WAKA_OIDC_ENDPOINT: "eW91c2hhbGxub3RwYXNz"
