apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: adguard=ghcr.io/adguard/server:2025.6.4
    argocd-image-updater.argoproj.io/adguard.update-strategy: digest
    argocd-image-updater.argoproj.io/adguard.update-regex: "ghcr.io/adguard/server:.*"
  name: adguard
  namespace: argocd
spec:
  destination:
    namespace: adguard
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: adguard
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
