apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: "*"
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
          global:
            leaderElection:
              namespace: cert-manager
    - path: cert-manager
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
