apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: coder=coder/server:latest
    argocd-image-updater.argoproj.io/coder.update-strategy: digest
  name: coder
  namespace: argocd
spec:
  destination:
    namespace: coder
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  sources:
    - chart: coder
      repoURL: https://helm.coder.com/v2
      targetRevision: "*"
      helm:
        releaseName: coder
        valuesObject:
          coder:
            resources:
              limits: {}
              requests: {}
            env:
              - name: CODER_PG_CONNECTION_URL
                valueFrom:
                  secretKeyRef:
                    name: coder-secret
                    key: CODER_PG_CONNECTION_URL
              - name: CODER_ACCESS_URL
                value: https://coder.lth.so
              - name: CODER_WILDCARD_ACCESS_URL
                value: "*.coder.lth.so"
              - name: CODER_OIDC_ICON_URL
                value: https://auth.lth.so/static/dist/assets/icons/icon.png
              - name: CODER_OIDC_ISSUER_URL
                value: https://auth.lth.so/application/o/coder/
              - name: CODER_OIDC_EMAIL_DOMAIN
                value: lth.so,naver.com
              - name: CODER_OIDC_SIGN_IN_TEXT
                value: Sign in with HomeLab
              - name: CODER_OIDC_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: coder-secret
                    key: CODER_OIDC_CLIENT_ID
              - name: CODER_OIDC_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: coder-secret
                    key: CODER_OIDC_CLIENT_SECRET
            serviceAccount:
              workspacePerms: true
              enableDeployments: true
              workspaceNamespaces:
                - name: coder-workspace
            service:
              enable: true
              type: ClusterIP
            ingress:
              enable: false
    - path: coder
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
