apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: "*"
      helm:
        releaseName: grafana
        values: |
          grafana.ini:
            server:
              domain: monitoring.lth.so
              root_url: "%(protocol)s://%(domain)s"
            auth.anonymous:
              enabled: true
              org_name: Main Org.
              org_role: Viewer
          persistence:
            type: pvc
            enabled: true
            volumeName: "grafana-pv"
            storageClassName: "local-path-retain"
            accessModes:
              - ReadWriteOnce
    - path: grafana
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
        istio.io/use-waypoint: waypoint
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
