apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: homarr=ghcr.io/homarr-labs/homarr:latest
    argocd-image-updater.argoproj.io/homarr.update-strategy: digest
  name: homarr
  namespace: argocd
spec:
  destination:
    namespace: homarr
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  source:
    path: homarr
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
