apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iperf3
  namespace: argocd
spec:
  destination:
    namespace: iperf3
    server: https://kubernetes.default.svc
  project: default
  source:
    path: iperf3
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: none
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
