apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cni
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: "*"
    helm:
      releaseName: istio-cni
      values: |
        profile: ambient
        global:
          platform: k3s
        cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        cniBinDir: /var/lib/rancher/k3s/data/current/bin
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
