apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: mongodb=public.ecr.aws/docker/library/mongo:latest
    argocd-image-updater.argoproj.io/mongodb.update-strategy: digest
  name: mongodb
  namespace: argocd
spec:
  destination:
    namespace: mongodb
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: mongodb
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
