apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime
  namespace: argocd
spec:
  destination:
    namespace: oneuptime
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: oneuptime
      repoURL: https://helm-chart.oneuptime.com/
      targetRevision: "*"
      helm:
        releaseName: oneuptime
        values: |
          storageClass: "local-path-retain"
          host: "status.limtaehyun.dev"
          externalPostgres:
            host: "postgres-service.postgres.svc.cluster.local"
            port: 5432
            database: "oneuptime"
            username:
              valueFrom:
                secretKeyRef:
                  name: oneuptime-secret
                  key: postgres-username
            password:
              valueFrom:
                secretKeyRef:
                  name: oneuptime-secret
                  key: postgres-password
          externalRedis:
            host: "redis-service.redis.svc.cluster.local"
            port: 6379
            database: 3
          clickhouse:
            enabled: true
            auth:
              username: "oneuptime"
              password:
                valueFrom:
                  secretKeyRef:
                    name: oneuptime-secret
                    key: clickhouse-password

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
