apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: outline=docker.getoutline.com/outlinewiki/outline:latest
    argocd-image-updater.argoproj.io/outline.update-strategy: digest
  name: outline
  namespace: argocd
spec:
  destination:
    namespace: outline
    server: https://kubernetes.default.svc
  project: default
  source:
    path: outline
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
