apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  destination:
    namespace: plane
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  sources:
    - chart: plane-ce
      repoURL: https://helm.plane.so/
      targetRevision: 1.4.1
      helm:
        releaseName: plane-app
        valuesObject:
          planeVersion: v1.2.0
          ingress:
            appHost: plane.lth.so
            enabled: false
          ssl:
            tls_secret_name: lth-tls
          external_secrets:
            app_env_existingSecret: plane-app-secrets
            doc_store_existingSecret: plane-doc-store-secrets
            live_env_existingSecret: plane-live-secrets
            rabbitmq_existingSecret: plane-rabbitmq-secrets
          env:
            cors_allowed_origins: https://plane.limtaehyun.dev
            default_cluster_domain: cluster.local
          postgres:
            local_setup: false
          redis:
            local_setup: false
          rabbitmq:
            local_setup: true
            storageClass: local-path
            assign_cluster_ip: true
          minio:
            local_setup: true
            storageClass: local-path
            assign_cluster_ip: true
          web:
            assign_cluster_ip: true
          space:
            assign_cluster_ip: true
          admin:
            assign_cluster_ip: true
          live:
            assign_cluster_ip: true
          api:
            assign_cluster_ip: true
    - path: plane
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
