apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  sources:
    - chart: kube-prometheus-stack
      helm:
        releaseName: prometheus
        valuesObject:
          alertmanager:
            enabled: false
          coreDns:
            enabled: false
          crds:
            enabled: true
          defaultRules:
            create: false
          fullnameOverride: prometheus-stack
          grafana:
            enabled: false
          kubeApiServer:
            enabled: false
          kubeControllerManager:
            enabled: false
          kubeEtcd:
            enabled: false
          kubeProxy:
            enabled: false
          kubeScheduler:
            enabled: false
          kubelet:
            enabled: true
            serviceMonitor:
              authorization:
                credentials:
                  key: token
                  name: prometheus-kubelet-token
                type: Bearer
          kube-state-metrics:
            fullnameOverride: kube-state-metrics
            prometheus:
              monitor:
                additionalLabels:
                  release: prometheus
          prometheus:
            enabled: false
          prometheus-node-exporter:
            fullnameOverride: node-exporter
            prometheus:
              monitor:
                additionalLabels:
                  release: prometheus
          prometheusOperator:
            fullnameOverride: prometheus-operator
            kubeletService:
              name: kubelet
            serviceMonitor:
              additionalLabels:
                release: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "*"
    - path: observability/prometheus
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
