apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: seafile=seafileltd/seafile-pro-mc:12.0-latest
    argocd-image-updater.argoproj.io/seafile.update-strategy: digest
spec:
  destination:
    namespace: seafile
    server: https://kubernetes.default.svc
  project: default
  source:
    path: seafile
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
