apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: spotify=ghcr.io/yooooomi/your_spotify_server:latest
    argocd-image-updater.argoproj.io/spotify.update-strategy: digest
  name: spotify
  namespace: argocd
spec:
  destination:
    namespace: spotify
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: spotify
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
