apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  sources:
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.92.4
      helm:
        releaseName: tailscale-operator
        parameters:
          - name: TS_KUBE_SECRET
            value: "tailscale-secret"
    - path: tailscale
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
