apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
    - jsonPointers:
        - /spec/externalName
      kind: Service
  sources:
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: "*"
      helm:
        releaseName: tailscale-operator
        values: |
          oauth:
            clientId:
              valueFrom:
                secretKeyRef:
                  name: operator-oauth
                  key: client_id
            clientSecret:
              valueFrom:
                secretKeyRef:
                  name: operator-oauth
                  key: client_secret
    - path: tailscale
      repoURL: git@github.com:noeulnight/homelab.git
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: none
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
