apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: vaultwarden=vaultwarden/server:testing
    argocd-image-updater.argoproj.io/vaultwarden.update-strategy: digest
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: vaultwarden
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
