apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: visualizer=benc-uk/kubeview:latest
    argocd-image-updater.argoproj.io/visualizer.update-strategy: digest
  name: visualizer
  namespace: argocd
spec:
  destination:
    namespace: visualizer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: visualizer
    repoURL: git@github.com:noeulnight/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
