apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/affine
    type: DirectoryOrCreate
