apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwoot
resources:
  - ./service-account.yml
  - ./secret.yml
  - ./service.yml
  - ./web-deployment.yml
  - ./worker-deployment.yml
  - ./db-migrate-job.yml
  - ./virtual-service.yml
