apiVersion: v1
kind: ConfigMap
metadata:
  name: solidtime-config
data:
  APP_NAME: solidtime
  VITE_APP_NAME: solidtime
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://time.lth.so
  APP_FORCE_HTTPS: "true"
  APP_ENABLE_REGISTRATION: "true"
  TRUSTED_PROXIES: 0.0.0.0/0,2000:0:0:0:0:0:0:0/3
  SUPER_ADMINS: "limtaehyun@lth.so"
  LOG_CHANNEL: stderr_daily
  LOG_LEVEL: debug
  DB_CONNECTION: pgsql
  DB_HOST: postgres-service.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_SSLMODE: prefer
  DB_DATABASE: solidtime
  DB_USERNAME: solidtime
  MAIL_MAILER: smtp
  MAIL_HOST: bridge-service.bridge.svc.cluster.local
  MAIL_PORT: "1025"
  MAIL_FROM_ADDRESS: limtaehyun@lth.so
  MAIL_FROM_NAME: solidtime
  MAIL_USERNAME: limtaehyun@lth.so
  QUEUE_CONNECTION: database
  FILESYSTEM_DISK: local
  PUBLIC_FILESYSTEM_DISK: public
  GOTENBERG_URL: http://solidtime-gotenberg-service.solidtime.svc.cluster.local:3000
