apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
type: Opaque
spec:
  encryptedData:
    api-token: AgAgtovo5DZ1BpAps+oo0Z8/hwVEAfSCr5Hy+gVCciA01nrj1q28ypjyx3RiXfjoqlPZ8sL/VJBrwc12dDCAxXmYzefvF7TLpjWKssbal3mJQ54GjPakdTfPyHQ3hLfZgfLW0fAg0L4abEZqMvIMrxrTljLsnSFixMMf3wcnFvetu4zVBhIu8lWdtbOrQFO3lNIWdtchvJ4lQmDwnWFISdULCT3PmA+0ioHnisXOSj76n6Up3bx4OLcllO814OP365rSJHyc/MOQs8OTygpLIVywQUfmQDWkU/xSV62FQs7+WKaFasLnyqknzKJzyBAcjbz2TCmYxebRvY0jqcNLxdFE6f2CaVPXSR/Z198M7ziVjkR/sxeNBtvKC/mOIpeTBx5A2LKZEvuKNghBIco4Nr6w9Z4TjODNPrpGSW+fqvprd5J8/gSuPpO7zNgizedo7Gv5fpkTFFFH3APEy8wBDFcHE3jeq1a+AZ3IEMPxFtAf/biG5znbYqf/PGclmgQzYKtv90FJgZuhWdQxh/CCuVrOWL5MqE82tWyEo8Mjkh2EccsgBssXsdDsRSiM6mzZ1jxONkhoNTnFWoCxxX6RXkMjd6U2457QwtMa+V8soAGEuRiI9ttG2+vxMlcpvj6LdUncZRgMaj+L7avZA09wgLnYydB8/Kn7fXH5i78TCAy0lu3i9YwL1FofCYkJZDPYJGRu9P+JTpkU5cU1UuHxcT9os2ji3fCm5pFfli45b8BeoAFF3SGY1MUM
