apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booklore-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBpeKcfqyS6OZ9GLwYmrrr/YCN87OJ8FxSR5V8OluNcUuHfwukKCgjAf3Yrese4HtR1AFix2h2GrLWWnNr5wOHqWDPOVnUTS84UuPbUwm0vjq8k3ywtC3cXaoqjFcYofJE6BbDRCc+vD9nd1t5WiaMN4UIwWOSEV+0nc0nEx/+UYK1/EMTzASwvo/mUIthHGDGa10eejiAp+msRI5TeMZBPIpq9dbkBQ+0xXydNKH3oP4XDp+xSn+cNKFSFi/nc83S5rtoO1YiLvTRpehUlrJxpBg6a/KPcyBb4HiQP1iNyBgRsWZ1kOo1VXdDQj9NlZw7zrL8a5HBg0IwgbGfqwIiEH4H/SJDYbHw/pbNA6iUdDhMWrIakKii58xy9+TDsMm54rTYfvFQCTWl9yeorsmpXpsTfQAFUrmUPut5z1mmsf4yf+3Ldii6OjwrgQYsauNSBHjyPcWIS6ruiukB5NB4W4z69rzmkXIsoxHi35dTFEKsjUKNinzd3TCHQU5xJYdLpRy5za4keXF2IRsfclKhPjKTtPpD4d/amYCWZxkjqECt4SYrd3as7yYD0rHpTjNdf35CNSGARO029V5XAcOcXJlaMHstk7sA7gHVGF5xByiMS/5sIc/EyQjmk/spryjYi20mIiz8qsBAUS8excPcAit+HaOszT+8KB364bGk/jOhYVqmcDUJLdF1zYGNUR6YcqsuPOcPVoGAC
  template:
    metadata:
      name: booklore-secret
      namespace: booklore
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"