apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: technitium
spec:
  hosts:
    - "dns.lth.so"
  gateways:
    - istio-ingress/public-gateway
  http:
    - route:
        - destination:
            host: ak-outpost-technitium.authentik.svc.cluster.local
            port:
              number: 9000
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=31536000; includeSubDomains
